services:
  db:
    image: postgres:17
    container_name: gameserver-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/db:/var/lib/postgresql/data